baseURL = "https://shwetank.netlify.com/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Shwetank Panwar | Blog"
[[menu.footer]]
URL = "tools"
name = "Projects"
weight = 2
[[menu.footer]]
URL = "contact"
name = "About me"
weight = 1
[[menu.main]]
URL = "contact"
name = "About Me"
weight = 1
[[menu.main]]
URL = "https://drive.google.com/file/d/1YBQib-dtJixDmpk2n-kBQ6wqcfUZX2JR/view?usp=sharing"
name = "Resume"
url = "https://drive.google.com/file/d/1MhpDev7L0qCTLX1pAYencHI3xZs83dF7/view?usp=sharing"
weight = 3
[[menu.main]]
URL = "tools"
name = "Projects"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Shwetank Panwar"
contact_form_action = "#"
copyright = "&copy; Shwetank Panwar | From [Gethugothemes](https://gethugothemes.com) All Rights Reserved"
description = "This is meta description"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/fusion_matching.png"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "Hi, I'm Shwetank Panwar. <br> I help people make sense of images and knowledge graphs"
[params.cta]
description = "That's great. I believe learning best happen with discussions. Just ping me and lets see if we can learn together. "
enable = false
image = "images/chat_logo.png"
title = "Are you too fascinated with the biology & data science?"
[params.cta.button]
enable = true
label = "Ping me"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = "Hey wait! Some nice blogs are on their way"
[params.search]
enable = true
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/pirate_geek"
[[params.social]]
icon = "ti-github"
link = "https://github.com/pshwetank"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/pshwetank/"
